
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.Button btnConvert;
	
	private global::Gtk.Entry tboxAmountEntry;
	
	private global::Gtk.Label lblMain;
	
	private global::Gtk.Label lblPesoAmount;
	
	private global::Gtk.Button btnClear;
	
	private global::Gtk.Button btnExit;
	
	private global::Gtk.Label lblEuroAmount;
	
	private global::Gtk.Label lblMarkAmount;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Currency Conversion");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnConvert = new global::Gtk.Button ();
		this.btnConvert.CanFocus = true;
		this.btnConvert.Name = "btnConvert";
		this.btnConvert.UseUnderline = true;
		this.btnConvert.Label = global::Mono.Unix.Catalog.GetString ("Convert");
		this.fixed2.Add (this.btnConvert);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnConvert]));
		w1.X = 35;
		w1.Y = 87;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.tboxAmountEntry = new global::Gtk.Entry ();
		this.tboxAmountEntry.WidthRequest = 82;
		this.tboxAmountEntry.CanFocus = true;
		this.tboxAmountEntry.Name = "tboxAmountEntry";
		this.tboxAmountEntry.IsEditable = true;
		this.tboxAmountEntry.InvisibleChar = '•';
		this.fixed2.Add (this.tboxAmountEntry);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.tboxAmountEntry]));
		w2.X = 111;
		w2.Y = 87;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.lblMain = new global::Gtk.Label ();
		this.lblMain.WidthRequest = 171;
		this.lblMain.HeightRequest = 33;
		this.lblMain.Name = "lblMain";
		this.lblMain.LabelProp = "Currency Converter";
		this.lblMain.UseMarkup = true;
		this.fixed2.Add (this.lblMain);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblMain]));
		w3.X = 123;
		w3.Y = 24;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.lblPesoAmount = new global::Gtk.Label ();
		this.lblPesoAmount.Name = "lblPesoAmount";
		this.lblPesoAmount.LabelProp = global::Mono.Unix.Catalog.GetString ("Peso Amount");
		this.fixed2.Add (this.lblPesoAmount);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblPesoAmount]));
		w4.X = 35;
		w4.Y = 203;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnClear = new global::Gtk.Button ();
		this.btnClear.CanFocus = true;
		this.btnClear.Name = "btnClear";
		this.btnClear.UseUnderline = true;
		this.btnClear.Label = global::Mono.Unix.Catalog.GetString ("Clear");
		this.fixed2.Add (this.btnClear);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnClear]));
		w5.X = 35;
		w5.Y = 123;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnExit = new global::Gtk.Button ();
		this.btnExit.CanFocus = true;
		this.btnExit.Name = "btnExit";
		this.btnExit.UseUnderline = true;
		this.btnExit.Label = global::Mono.Unix.Catalog.GetString ("Exit");
		this.fixed2.Add (this.btnExit);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.btnExit]));
		w6.X = 34;
		w6.Y = 158;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.lblEuroAmount = new global::Gtk.Label ();
		this.lblEuroAmount.Name = "lblEuroAmount";
		this.lblEuroAmount.LabelProp = global::Mono.Unix.Catalog.GetString ("Euro Amount");
		this.fixed2.Add (this.lblEuroAmount);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblEuroAmount]));
		w7.X = 152;
		w7.Y = 203;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.lblMarkAmount = new global::Gtk.Label ();
		this.lblMarkAmount.Name = "lblMarkAmount";
		this.lblMarkAmount.LabelProp = global::Mono.Unix.Catalog.GetString ("Mark Amount");
		this.fixed2.Add (this.lblMarkAmount);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.lblMarkAmount]));
		w8.X = 275;
		w8.Y = 203;
		this.Add (this.fixed2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 403;
		this.DefaultHeight = 281;
		this.lblMain.MnemonicWidget = this.lblMain;
		this.lblPesoAmount.MnemonicWidget = this.lblPesoAmount;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnConvert.Clicked += new global::System.EventHandler (this.OnBtnConvertClicked);
		this.btnClear.Clicked += new global::System.EventHandler (this.OnBtnClearClick);
		this.btnExit.Clicked += new global::System.EventHandler (this.OnBtnExitClick);
	}
}
